on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
            
      - run: ls -la

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: '18.202.28.195'
          username: 'ubuntu'
          key: ${{ secrets.ANSIBLE }}
          port: "22"
          source: "index.html"
          target: "/var/www/html/"