on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
            
      - run: ls -la

      - run: scp -i ${{ secrets.ansible }} ./index.html ubuntu@18.202.28.195:/var/www/html/
